### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by chiadikaeleh**

### CODE REVIEW

**Comment by junchuanwang** [comment]
Any reason to merge this?

**Comment by evanw555** [comment]
What's the reasoning for this PR? Are you removing this task configuration because it has no effect?

**Comment by evanw555** [comment]
Hi @chiadikaeleh just pinging again about this. Please help us to understand the purpose of this PR. If we don't get a response, we'll just close this PR due to inactivity.

**Comment by chiadikaeleh** [comment]
Hi!

Can you close this PR?

Chiadika

**Pull request closed without merging**
