### PR TITLE
Update SetMode.java

### PR DESCRIPTION
**Pull request by ComboZhc**
Polish javadoc in SetMode

### CODE REVIEW

**Comment by xma000** [comment]
Hi Chao,

Thanks for fixing it. For LinkedIn engineer, please follow
https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Pegasus+Git+Workflow to
make changes to Pegasus.

Xiao

**Comment by ComboZhc** [comment]
Sure. I will.

But Pull Request on Github is much easier than the formal process :)

**Comment by kvidhani** [comment]
I gave you a ship it. The reason we suggested an alternative to the pull
request is that we have no way of taking a pull request from GitHub and
propagating it to gitoroius which is where LinkedIn's version of pegasus
resides.

- Karim

**Comment by kvidhani** [comment]
Sorry I hit send too early.

Hence the reason we ask you commit in this way is so that once your commit
makes it through, it will then be mirrored over to the open source version.

**Pull request closed without merging**
