### PR TITLE
Delete mainCopyPdscSchemas.

### PR DESCRIPTION
**Pull request by tjni**
All LinkedIn references to this task have been removed.

This is a backwards incompatible change, so I will be happy to push it to a major version branch if we have such policies.

(Actually, there is still one usage that remains in code search, but I have a PR to the team to resolve it.)

### CODE REVIEW

**Comment by nickibi** [comment]
Overall, the changes look good to me. As you mentioned, there is still one usage that remains. I would prefer to keep this PR one until there is no usage at all.

**Comment by tjni** [comment]
The final build usage has been removed. In code search, there is only a remnant in a JSON file in a build-scans-samza-jobs test resource.

**Comment by tjni** [comment]
I updated this to also delete the mainDestroyStaleSchemas task.

All internal usages have been removed, according to code search, except:

1. datarealm-dummy-itm (this is a bug in the code search crawler)
2. datarealm-lmsauthzplayground (owner will delete this product after experimentation)
3. datarealm-restaurants-mparthas (owner wants to leave it untouched)
4. datarealm-symtable-registry (product will be deleted)
5. datarealm-ufo-test (product has been deleted)
6. datarealm-eventtest (product has been deleted)

**Comment by nickibi** [comment]
Rebased master and moved to a new PR: https://github.com/linkedin/rest.li/pull/734

**Pull request closed without merging**
